-- expects the csv on the classpath (src/main/resources)
INSERT INTO VEHICLE (NAMEX, YEARX, SELLINGPRICE, KMDRIVEN, FUEL, SELLERTYPE, TRANSMISSION, OWNER, MILEAGE, ENGINE, MAXPOWER, TORQUE, SEATS)
SELECT *
FROM CSVREAD('classpath:Auto v2.csv');
